language: node_js
node_js:
  - node

install:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: AKIAIO42DM7NWEB4GAOA
  endpoint: s3-website.eu-west-3.amazonaws.com
  region: eu-west-3
  secret_access_key:
    secure: bRUeV93kIIxHxC6VoeKud/fPF7qIb7dBDqtLixV037h87cE1PSQwmVHM073CjsdcUsVvkl2q5JKGTg4LhMj1nCQPziIwJcKyeZUwkjG6ZUB9hWKWOjKrLp56YtiIk2M/xXVNtypPozTZNBPHg3EPJhHFOp1Q+2FpoQ43iJRKsTMmB/8i8sGhzyEDuR2V4YbApp+IP+Ffg6ffmjnpeQI+ngWtj0Ynx8wocad+o9l/SkPjYxG8AlQQNqQ7d49fr/ubpWEl7Uztssx8gfXPiams2aQxmRmGpHF59cOAof3Ziw18PlKBzXqcTSGeY46P8yBVwH2c5iNWV1tnFKxW8/BFE6a+JY4s2C3gE7FXSXqjiqOOuohfzV/l+r8ic0nACcCA0wlOnQHo9FHjafw7lpciiVNEH0qG47t/QuTl65R3IOqIDz1v/IYNUlLSPfzJ7N4MsUomKY8ATIEBsnfh3KR8FIQlOrbCJOr6VkpZxEw96E79I2vQpxV0WHX/htGrbLIjLx7oqGfrqnEnlfBhL0nAorOu+UpfkBhr2SJKfy+0XtwV42KZpUb9ZfxFpPWzL99TqhBwn0Kf0hBrVOSxDD3yaXyDSY4c2IVadpgP2B6Mmhe8NtEB9RbVW1bEGA5H5Cfv3UKS3KrcLSVwMH+B6TJeiRv7EwA1rIhxC8Ovy1SGbr4=
  bucket: profile.gaelmusi.com
  skip_cleanup: true
  local-dir: build
  acl: bucket_owner_full_control
  on:
    repo: GaelWM/profile.gaelmusi.com
