language: node_js
node_js:
  - node

install:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: AKIAI6IKW3HG5C6XRL4A
  secret_access_key:
    secure: a1jerDQcg6ZzrP1PMW95Z8pewJQq5/1ZmdRyHfQ6An8JgRIyNsYp/XXcQZc2UebAyqQuphrqt0uI266aV7ISh2RkILxWxsRd721IFWKM3bCjzvLv8XMuRiL0pcUybeYxW6KA0XF0qjbFhC0TGDYf8EX7TUCoQfwJSYw9CHDXlKNic46dDenxD8U6SXeZpxNHe8HpZVu/3J0Nk9alRMuV9TUhwkq3oo1HBBNgiEHHJvwp5QZL4JBH5qKGec30F4CURwmhLg8neHMavJZoJ3ujEnYkOr+Amt66gVIQ2UGejvuBM+CDspNItADWL45xj+JEfctYl9LQfhJqwDd+kfVouAjoipAswJxNxQvSIxjbhukEZEwSht7S6XUb711xkFkK3yzNCqsVwy7iiXV1MjRA1gmWZixCPYnoHfFpHGh90xbMemthXArL/66GyoHzAMp8LP5bm+IMfkwC0UoeUy5HhW0n6P7xwhdsGCEKVX06BvjNv6pRSw0ZI6wv34AQllFVOZFmzaefS9MRVi2RszVqb9BC19VXDKETJqn+oPE58cbR5o0QY82fd1ndQZ71Yq8uY/sOOc21Qt8ABCgko9KKphES9eV1sXxfoST1h/oRDaxGPR9r8+q6cBYuny+UNZUqH5otLlMpVtkNYqhgdA/UrA0Llfsalf4+EdZ5/rUNkYA=
  bucket: profile.gaelmusi.com
  local-dir: build
  acl: bucket_owner_full_control
  on:
    repo: GaelWM/profile.gaelmusi.com
