language: node_js
node_js:
  - node

install:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build


deploy:
  provider: s3
  access_key_id: AKIAIGD77HFYDYZN5BVQ
  endpoint: s3-website.eu-west-3.amazonaws.com
  region: eu-west-3
  secret_access_key:
    secure: vccW8Kj7PYmTj/vzFTyVj31kFAMDnxJGX+1toj1D2Dt+2hUXgYtvtf0oMyUzAwZUIOyXE4m7rIz6lbPGod0cDarqQB0k2NivWAhsbI72+gzR+Tyb+B8ZzlG68FQXhxD7e8iKAfX+ixs7XM+MHbWQ2ZBltYsOLST99lxj/iyNG+nQEAbI8vSoShoCTK2Y4FYx555DpsNw5zgWtaF4gn/4PIJpihJO0CgSaVB9mBsO2MDJzftjTtSz8W+/DjyvNOmT4L8h6b2Oj1LuZ8qoLUunY7OckQk++XcLG0njJSvqK3mMSw4GaLtSCMGW8ITZWpJejXJhtabthzX7HwSS8v9uLuA1uv6S/zwQSgrGvMhIJKtrGfC0KC11A6m6MAcWQhTAOsIsMnt8WYpnj1lIdn4SnRCYHgKZ4qbLF6GsG3WbEglaardEXO4rzICcvNiFTRpHqviv/iJ/E3rTwsdml0gVCSZMPShq4rtfJEZfCVAWtdwNa9mD7oQJecSM5e4o43MBrdL2TH8T3lktlEatIEdlTgPQ5WSO56OMFWM8hJHcgZu6B0NVAf9zUqDTlRm/koHSHOIgukPTs/w8fJGSqH3mD2LZsT19KAxrzLyYTObHagGJmRjeBk2Unmf1Ol6IpPtsyVO6VgK8P18lPCRQiijocwfcm5TnttCRUFs+Rk4A910=
  bucket: profile.gaelmusi.com
  local-dir: build
  skip_cleanup: true
  acl: bucket_owner_full_control
  on:
    repo: GaelWM/profile.gaelmusi.com
