language: node_js
node_js:
  - node

install:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: AKIAIGD77HFYDYZN5BVQ
  endpoint: s3-website.eu-west-3.amazonaws.com
  region: eu-west-3
  secret_access_key:
    secure: AG8LZktC/dguhY3Iu7MNDIUu2m9qYiNG8qRUg7VC8H/eqn1x4u+p3LfoEklaYNFRCLjxjnETeot6NvCPTO6e/RzonDiwmZ2kNNmtHwOhZE2rFBAbzuSI5+wiWQ8Ux2EniGHjfT+aHiLTHTLZ8uae2PC4nv4DzucZH9Rk2OhKFScrhEX/8CSzoS7Byr2j+E6Xi6daS2sgtRZvx7d5RXlexc2GuV18BbhrVsUS/O4uBxhH2RFmkxh1kNh6JDuCh6yIzvO0ACYgaovby5IW8pY2yPM47crr0xb4SfsUCJdcASm9TXsAiYUzaN3fy7cikwsDxb+mHwpXPUdQpX0Z1vWxwOcVvV6j408dJR1/t2pEOrlTEDQF+EoQ/FpyWYArCjARu7M19+EcePFSAnNARgakcUmV2Zcl0HfUGENSHtY4i37ftKTpIukDk7sTjRqASI2JMZxxrn1sYJvyZgGWkJMpIlHkSZunRIWsl/W9LX23XdtTjfKRR7vQ/Qxw2u9yoWgeiodvNvAveylmnYN9CnEP2DuWiBjdrOkZuAjhIkQlmsvBjWB8Ou4uuLX19Uw/MRMKL/nVxE+b0gJJ2BnloItARRT0Ke3RXYKnzMIL0t6SGcSMEg9mt3+nmDi0HawhfeZlvJkW9hN2O/F93kO6rg57+zpG50zdX8T1xaG64eAhj30=
  bucket: profile.gaelmusi.com
  skip_cleanup: true
  local-dir: build
  acl: bucket_owner_full_control
  on:
    repo: GaelWM/profile.gaelmusi.com
